language: python
install:
  - pip install -r requirements.txt
script:
  - ./create-config
  - ./safeway-coupons -c config.ini

env:
  global:
    - EMAIL_SENDER=${EMAIL_SENDER}

jobs:
  include:
    - stage: "run safeway-coupons"
      env:
        - SAFEWAY_ACCOUNT=${USER1}
        - SAFEWAY_PASSWORD=${PASS1}
        - NOTIFY_EMAIL=${USER1}
    -
      env:
        - SAFEWAY_ACCOUNT=${USER2}
        - SAFEWAY_PASSWORD=${PASS2}
        - NOTIFY_EMAIL=${USER2}
    -
      env:
        - SAFEWAY_ACCOUNT=${USER3}
        - SAFEWAY_PASSWORD=${PASS3}
        - NOTIFY_EMAIL=${USER3}
    -
      env:
        - SAFEWAY_ACCOUNT=${USER4}
        - SAFEWAY_PASSWORD=${PASS4}
        - NOTIFY_EMAIL=${USER4}
    -
      env:
        - SAFEWAY_ACCOUNT=${USER5}
        - SAFEWAY_PASSWORD=${PASS5}
        - NOTIFY_EMAIL=${USER5}
